[FE] Layout for Add Item Page
framgia/sph-els-inventory pull request #8
Opened 2022-08-11 03:15 UTC by misterRenz

## Task Link
- https://app.asana.com/0/1202718774787420/1202733801001941/f

## Commands
- npm start

## Pre-conditions
- The Frontend developer must be working in the frontend folder of the repository

## Expected Output
- It will display the Add Item Form
- It will display a button that states "Submit"
- Button will not work for now because it still has no function on [BE] but I implemented a function on it if the users press submit it will display the data of the add item on the console.log

## Notes
- To test the add item page, go to App.js and return <AddItemPage />

## Screenshots
![image](https://user-images.githubusercontent.com/108708360/184058850-4408f42e-478a-43dc-8a7c-438a19e53953.png)

2022-08-11 03:39 UTC, karlolee50 commented on frontend/src/components/button/index.js
> +const SIZE = ["btn--small", "btn--large"];
no need for this one. just pass directly as a prop

2022-08-11 03:39 UTC, karlolee50 commented on frontend/src/components/button/index.js
> +const Button = ({ children, type, onClick, buttonStyle, buttonSize }) => {
set default value of buttonStyle and buttonSize here

2022-08-11 03:39 UTC, karlolee50 commented on frontend/src/components/button/index.js
> +  const checkButtonSize = SIZE.includes(buttonSize) ? buttonSize : SIZE[0];
you can remove these

2022-08-11 03:40 UTC, karlolee50 commented on frontend/src/components/button/index.js
> +      className={`btn ${checkButtonStyle} ${checkButtonSize}`}
```suggestion
      className={`btn ${buttonStyle} ${buttonSize}`}
```

2022-08-11 03:44 UTC, karlolee50 commented on frontend/src/components/input-text-field/index.js
> +      <div>
will the layout be broken if we remove the div?

2022-08-11 03:45 UTC, karlolee50 commented on frontend/src/components/input-text-field/index.js
> +        }}
refactor this to pass just the class name like 'width-lg' and update the css file

2022-08-11 03:45 UTC, karlolee50 commented on frontend/src/components/inputdate/index.js
> +          }}
refer to my previous similar comment

2022-08-11 03:46 UTC, karlolee50 commented on frontend/src/pages/layout-add-item-page/index.css
> +.addItemPage {
please rename the 'layout-add-item-page' folder to 'add-item'

2022-08-11 03:47 UTC, karlolee50 requested changes
please check

2022-08-11 07:18 UTC, misterRenz commented
Recenty made a new commit using web-editor because of newly merge from francis' branch and it had conflict with my app.js

2022-08-11 12:54 UTC, karlolee50 commented on frontend/src/components/input-text-field/index.js
> +        className="width-lg"
you can pass the classname as a prop. don't forget to set a default value

2022-08-11 12:54 UTC, karlolee50 commented on frontend/src/components/input-text-field/index.js
> +  inputFieldWidth,
remove if not being used anymore

2022-08-11 12:54 UTC, karlolee50 commented on frontend/src/components/input-text-field/index.js
> +  inputFieldDisplay,
remove if not being used anymore

2022-08-11 12:55 UTC, karlolee50 commented on frontend/src/components/inputdate/index.js
> +  inputFieldWidth,
remove if not used

2022-08-11 12:55 UTC, karlolee50 commented on frontend/src/components/inputdate/index.js
> +          className="width-lg"
same as my previous comment. pass the classname as a prop and set default value

2022-08-11 12:56 UTC, karlolee50 commented on frontend/src/pages/add-item/index.js
> +            getReserveData={(reservedata) => setReserve(reservedata)}
is it possible to use camel casing here?
```suggestion
            getReserveData={(reserveData) => setReserve(reservedata)}
```

2022-08-11 12:56 UTC, karlolee50 commented on frontend/src/pages/add-item/index.js
> +              getDateData={(fromdatedata) => setFromDateInput(fromdatedata)}
camel casing here as well

2022-08-11 12:56 UTC, karlolee50 commented on frontend/src/pages/add-item/index.js
> +              getDateData={(todatedata) => setToDateInput(todatedata)}
use camel casing

2022-08-11 12:56 UTC, karlolee50 requested changes
please check

2022-08-12 03:52 UTC, karlolee50 approved these changes

2022-08-12 03:52 UTC, merged